version: '3.7'
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=Patient_cards
      - MYSQL_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    expose:
      - '3307'
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=Patient_cards
    volumes:
      - /home/developer/mongodb/database:/data/patient_cards
    ports:
      - 27017:27017
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elastichq:
    image: elastichq/elasticsearch-hq
    container_name: elastichq
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
      - HQ_DEBUG=True
      - HQ_ENABLE_SSL=True
      - HQ_VERIFY_CERTS=False
      - HQ_CA_CERTS=/usr/local/share/ca-certificates/MYCA.crt
    ports:
      - 5000:5000
    networks:
      - esnet

volumes:
  elasticsearch-data:
    driver: local
networks:
  esnet:
    driver: bridge